# Generated by Django 4.1.6 on 2023-02-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/blankimage.png', upload_to='images/users'),
        ),
    ]
