# Generated by Django 4.1.6 on 2023-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
